export const myths = [
    {claim:"Eating papaya causes miscarriage",verdict:"Partly true",col:"var(--amber)",bg:"var(--amber-pale)",bdr:"var(--amber-bdr)",explanation:"Raw, unripe papaya contains latex which can trigger uterine contractions. Ripe papaya in small amounts is generally considered safe, but most doctors advise avoiding it entirely in the first trimester — not worth the risk."},
    {claim:"Saffron milk makes the baby fair",verdict:"False",col:"var(--rose)",bg:"var(--rose-pale)",bdr:"var(--rose-bdr)",explanation:"Skin colour is determined entirely by genetics. Saffron has no effect on the baby's complexion. That said, saffron milk in moderation is harmless and may help with sleep — just not for this reason."},
    {claim:"You should eat for two",verdict:"False",col:"var(--rose)",bg:"var(--rose-pale)",bdr:"var(--rose-bdr)",explanation:"In the first trimester you need almost no extra calories. By the third trimester, only about 300–450 extra calories per day — roughly one banana and a small bowl of dal. Overeating increases gestational diabetes risk."},
    {claim:"Sex during pregnancy harms the baby",verdict:"False",col:"var(--forest)",bg:"var(--forest-pale)",bdr:"var(--forest-bdr)",explanation:"For a normal pregnancy with no complications, sex is completely safe throughout. The baby is protected by the amniotic sac and cervical mucus plug. Your doctor will tell you if there are specific reasons to abstain."},
    {claim:"Sitting cross-legged affects the baby's position",verdict:"False",col:"var(--forest)",bg:"var(--forest-pale)",bdr:"var(--forest-bdr)",explanation:"There is no evidence that sitting cross-legged affects fetal positioning. Baby's position is determined by their own movement, the shape of your uterus, and your pelvic anatomy — not how you sit."},
    {claim:"A solar eclipse can cause birth defects",verdict:"False",col:"var(--forest)",bg:"var(--forest-pale)",bdr:"var(--forest-bdr)",explanation:"This is cultural belief with no scientific basis. UV radiation during an eclipse is no different from a regular cloudy day. You can go outside, eat, and carry on normally."},
    {claim:"Coconut water makes the baby's skin fair",verdict:"False",col:"var(--rose)",bg:"var(--rose-pale)",bdr:"var(--rose-bdr)",explanation:"Skin tone is genetic, full stop. Coconut water is genuinely good for hydration and electrolyte balance during pregnancy — drink it for those reasons, not for this one."},
    {claim:"Ghee helps with normal delivery",verdict:"Unproven",col:"var(--amber)",bg:"var(--amber-pale)",bdr:"var(--amber-bdr)",explanation:"There is no clinical evidence that consuming ghee in late pregnancy lubricates the birth canal or makes delivery easier. Ghee is a healthy fat and fine in moderation — but don't eat it for this purpose."},
    {claim:"AC and cold air harms the baby",verdict:"False",col:"var(--forest)",bg:"var(--forest-pale)",bdr:"var(--forest-bdr)",explanation:"Air conditioning is fine during pregnancy. Your body regulates temperature well, and the baby is insulated by amniotic fluid. In fact, overheating (especially in early pregnancy) is the actual concern — staying cool is beneficial."},
    {claim:"You can't exercise during pregnancy",verdict:"False",col:"var(--forest)",bg:"var(--forest-pale)",bdr:"var(--forest-bdr)",explanation:"Moderate exercise is actively recommended during a normal pregnancy. Walking, swimming, and prenatal yoga are excellent. Exercise reduces gestational diabetes risk, improves mood, and can shorten labour. Always check with your doctor first."},
  ];