export const COMMON_SYMPTOMS = {
    "cramping": {
      label: "Cramping", emoji: "😖",
      status: "Usually normal ✅",
      means: "Round ligament pain or uterine stretching is very common in week 8. Your uterus is growing rapidly.",
      tryThis: "Rest, change position, warm (not hot) water bottle on lower back. Gentle walking can help.",
      callIf: "Heavy bleeding, severe pain that doesn't ease, fever above 100.4°F, or pain on one side only.",
      questions: ["Is cramping normal this early?","What's the difference between round ligament pain and something serious?","Does cramping mean I should rest completely?"],
      context: "Cramping in early pregnancy. Key facts: round ligament pain is most common cause in T1, uterus growing rapidly, implantation cramping also possible. Progesterone causes uterine relaxation which can feel like cramps.",
    },
    "nausea": {
      label: "Nausea", emoji: "🤢",
      status: "Very common ✅",
      means: "Week 8 is peak nausea for most women. HCG hormone levels are at their highest right now.",
      tryThis: "Eat small amounts every 90 minutes. Keep crackers by the bed. Ginger biscuits, coconut water, cold foods smell less.",
      callIf: "Unable to keep any fluids down for 24 hours, signs of dehydration (dark urine, dizziness), weight loss.",
      questions: ["When will the nausea peak and stop?","What can I eat right now that won't make me sick?","Is my nausea worse than normal?"],
      context: "Morning sickness / nausea in week 8 pregnancy. Key facts: HCG peaks at weeks 8-10, affects 70-80% of women, usually resolves by week 12-14. Hyperemesis gravidarum (severe) affects 1-2%. Indian context: ginger, coconut water, poha, cold foods, small frequent meals help. Vitamin B6 can reduce nausea.",
    },
    "spotting": {
      label: "Spotting", emoji: "🩸",
      status: "Often normal, monitor carefully ⚠️",
      means: "Light spotting (pink or brown) can occur from implantation, cervical sensitivity, or subchorionic bleeding.",
      tryThis: "Rest, avoid intercourse until you've spoken to your doctor. Note the colour and amount.",
      callIf: "Bright red bleeding, clots, heavy flow like a period, cramping with bleeding — call doctor today.",
      questions: ["How do I know if this is serious?","What colour spotting is okay vs worrying?","Should I go to the doctor today?"],
      context: "Spotting / light bleeding in week 8 pregnancy. Key facts: implantation bleeding usually week 6-7, subchorionic hematoma common, cervical ectropion makes cervix more sensitive. Brown/pink = old blood, usually less urgent. Bright red + cramping = see doctor same day.",
    },
    "headache": {
      label: "Headache", emoji: "🤕",
      status: "Common in T1 ✅",
      means: "Blood volume increases 50% during pregnancy. Hormonal shifts and dehydration both cause headaches.",
      tryThis: "Drink 2–3 glasses of water immediately. Rest in a dark room. Paracetamol (not ibuprofen) is safe if needed.",
      callIf: "Severe headache with vision changes, swelling in face/hands, or headache after week 20 — could be preeclampsia.",
      questions: ["Is paracetamol safe to take?","Why are my headaches worse now than before pregnancy?","How much water should I be drinking?"],
      context: "Headaches in week 8 pregnancy. Key facts: blood volume expanding causes vessel dilation, oestrogen fluctuation triggers migraines, dehydration major cause. Paracetamol (acetaminophen) safe. Ibuprofen/aspirin should be avoided. Caffeine withdrawal common trigger in T1.",
    },
    "no movement": {
      label: "No movement felt", emoji: "👶",
      status: "Normal before week 18 ✅",
      means: "You won't reliably feel movement until week 18–22. At week 8 baby is only 1.6cm — too small to feel.",
      tryThis: "Nothing to do right now. Start kick counting from week 28 when movements become regular.",
      callIf: "If you've been feeling movement and it suddenly stops after week 24, call your doctor the same day.",
      questions: ["When will I first feel movement?","What does movement feel like at first?","Should I be worried I don't feel anything?"],
      context: "Fetal movement in week 8 pregnancy. Key facts: at week 8 baby is 1.6cm and movements not perceptible. First-time mothers feel movement (quickening) at 18-22 weeks, experienced mothers at 16-18 weeks. Sensation described as butterflies, bubbles, or flutters initially.",
    },
    "acidity": {
      label: "Acidity", emoji: "🔥",
      status: "Very common ✅",
      means: "Progesterone relaxes the valve between stomach and oesophagus. Stomach acid refluxes more easily.",
      tryThis: "Eat small meals. Don't lie down for 30 mins after eating. Cold milk, coconut water, banana can help.",
      callIf: "Severe chest pain, difficulty swallowing, or if it's affecting your ability to eat at all.",
      questions: ["Why is my acidity so much worse now?","What Indian foods make acidity better or worse?","Is it safe to take antacids?"],
      context: "Acidity / heartburn / GERD in week 8 pregnancy. Key facts: progesterone relaxes lower oesophageal sphincter, uterus will press on stomach later. Indian context: spicy food, chai, coffee worsen symptoms. Coconut water, cold milk, banana, jeera water help. Antacids with calcium/magnesium generally safe — check with doctor.",
    },
    "constipation": {
      label: "Constipation", emoji: "😣",
      status: "Very common ✅",
      means: "Progesterone slows digestion. Iron supplements (if you've started) also cause constipation.",
      tryThis: "Increase water intake significantly. Prunes, papaya (ripe only), fibre-rich foods. Gentle walking helps.",
      callIf: "No bowel movement for more than 5 days, severe pain, or blood in stool.",
      questions: ["My iron tablets are making it worse — what can I do?","Which Indian foods help constipation?","Is it safe to use a laxative?"],
      context: "Constipation in week 8 pregnancy. Key facts: progesterone slows gut motility, iron supplements worsen it, growing uterus adds pressure later. Indian context: isabgol (psyllium husk), warm water with lemon, prunes, ripe papaya, moong dal, green vegetables help. Stimulant laxatives not recommended — osmotic laxatives like lactulose generally considered safer.",
    },
    "swelling": {
      label: "Swelling", emoji: "🦶",
      status: "Mild swelling is normal ✅",
      means: "Some swelling, especially in feet and ankles, is normal from increased blood volume.",
      tryThis: "Elevate feet when resting. Stay hydrated. Avoid standing for long periods.",
      callIf: "Sudden or severe swelling, swelling in face or hands, or swelling with headache — signs of preeclampsia.",
      questions: ["Why does drinking more water actually help swelling?","When is swelling a sign of something serious?","What can I do at work when I can't elevate my feet?"],
      context: "Oedema / swelling in pregnancy week 8. Key facts: blood volume increases 40-50%, body retains more sodium and fluid. Ankle/foot swelling common especially in T3. Facial/hand swelling with headache = preeclampsia warning sign. More water reduces retention counterintuitively. Compression socks help.",
    },
    "discharge": {
      label: "Discharge", emoji: "💧",
      status: "Usually normal ✅",
      means: "Increased clear or white discharge (leucorrhoea) is normal and protective during pregnancy.",
      tryThis: "Wear breathable cotton underwear. Don't douche or use scented products.",
      callIf: "Yellow, green, grey, or foul-smelling discharge, or discharge with itching/burning — signs of infection.",
      questions: ["How do I know if the discharge is normal?","Is it safe to use panty liners throughout pregnancy?","What does abnormal discharge look like?"],
      context: "Vaginal discharge in week 8 pregnancy. Key facts: leucorrhoea (white/clear discharge) increases due to oestrogen and increased blood flow. Normal = white/clear, mild smell, no itching. Bacterial vaginosis and yeast infections more common in pregnancy. BV linked to preterm birth if untreated — needs antibiotics.",
    },
    "sleep": {
      label: "Sleep", emoji: "🌙",
      status: "Very common ✅",
      means: "Progesterone causes fatigue but paradoxically disrupts deep sleep. Anxiety and frequent urination don't help.",
      tryThis: "Sleep on your left side. Pillow between knees. Avoid screens 30 mins before bed.",
      callIf: "Severe insomnia affecting daily functioning — speak to your doctor about safe options.",
      questions: ["Why am I exhausted but can't sleep?","Is sleeping on my back harmful this early?","What position is best for pregnancy sleep?"],
      context: "Sleep disturbance in week 8 pregnancy. Key facts: progesterone is sedating but reduces REM sleep quality. Frequent urination (nocturia) starts early. Left side sleeping improves blood flow to placenta and kidneys — becomes important in T2/T3. Back sleeping fine in T1. Pregnancy pillow helps alignment. Vivid dreams common due to hormones.",
    },
    "mood swings": {
      label: "Mood swings", emoji: "🎭",
      status: "Very common ✅",
      means: "HCG and progesterone surge causes rapid emotional shifts. Week 8 is one of the most emotionally volatile periods of pregnancy.",
      tryThis: "Name what you're feeling without judging it. Short walks help regulate mood. Tell your partner it's hormonal, not personal.",
      callIf: "Persistent low mood lasting more than two weeks, inability to function, or thoughts of self-harm — speak to your doctor.",
      questions: ["Is it normal to cry for no reason?","How do I explain mood swings to my partner?","When do mood swings usually settle down?"],
      context: "Mood swings in week 8 pregnancy. Key facts: oestrogen and progesterone directly affect serotonin and dopamine. HCG peaks at weeks 8-10, heightening emotional sensitivity. Anxiety about the pregnancy, exhaustion, and nausea compound emotional instability. Usually improves significantly in T2 when hormones stabilise. Prenatal depression affects 10-15% of women — persistent low mood is not just 'hormones' and needs medical attention.",
    },
  };